### ISSUE TITLE
fixing the bugs

### ISSUE THREAD

**Issue by marielletaboas** [mariellebeusch/webpro-and-friends#2]
If you were in a group, you could alert each other to issues. I'm doing a monologue right now. Stefanie?

**Comment by mariellebeusch** [comment]
Fixes #2

**Comment by mariellebeusch** [comment]
Reopen this issue for tests

**Comment by marielletaboas** [comment]
Reopen this issue for tests

**Comment by marielletaboas** [comment]
close it
